# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.100-rc.1
    - name: Run
      run: dotnet run update_casks.cs
    - name: Commit changes if any
      run: |
        git config --global user.name "junian.dev bot"
        git config --global user.email "bot@junian.dev"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "dotnet version update"
          git push
        else
          echo "No changes to commit."
        fi
